### ISSUE TITLE
psd.js 한계

### ISSUE THREAD

**Issue by Rockheung** [Artia-Inspirenet/painting-lab#2]
[Source: meltingice/psd.js](https://github.com/meltingice/psd.js)

1.  user가 서버에게 하나 이상의 특정 레이어를 mark하여 request를 보낼 수 있는가? 
    *가능해 보인다.*
2. 브라우저단에서 PSD를 작성하여 저장할 수 있나? 
    *이 라이브러리로는 불가능하다.*

**Comment by hukim1112** [comment]
고생하셨습니다. 2번 항목에 대해서 약간의 고생이 있겠지만 가능할거라고 믿습니다. 그 부분은 제가 join해서 해결하도록 해요.
