### ISSUE TITLE
업로드된 PSD를 BE에서 얼마나(Period 측면) 가지고 있을지

### ISSUE THREAD

**Issue by Rockheung** [Artia-Inspirenet/painting-lab#4]
업로드된 PSD 파일을 최종적으로 User에게 주려면 서버에서 메모리에 올려진 상태든(pytoshop.load()) 파일로 떨궈져 있든 어떤 형태로든 서버가 가지고 있어야 하리라는 생각이 듭니다. 
기존 레이어를 픽셀 단위의 이미지로 (PNG 형태로든 뭐든 간에) 추출하여 다시 PSD를 재작성하게 되면 원래의 PSD와는 완전히 다른 PSD가 됩니다.
현재 다루고 있는 pytoshop에서 PSD 파일에 있는 다양한 설정값, path, 등의 수많은 _그것_ 들을 그대로 바닥부터 재생성할 수 있을지 확신이 들지 않습니다. 그렇지 않다면 일단 확인된 기능 - _새 레이어 추가_ 등 - 만 신뢰할 수 있다고 보는게 좋지 않을까 합니다.

**Comment by hukim1112** [comment]
좋은 의견입니다. 

1. pytoshop에서는 모두 class를 정의해두고 하나의 object로 다루고 있고 기술 문서를 통해 모든 format을 공개하고 있습니다. 만약 우리가 적절한 meta data들을 정해줄 수 있다면 방법을 알아내는데 고생하겠지만 새 psd 파일을 만들 수 있을거라 생각합니다.
2. 그러나 새로운 psd 파일을 만들 이유는 없을 거라 생각하고 말씀하신대로 가지고 있던 원본 psd에 새 레이어를 추가하는 방법이 될 겁니다. 하지만 그곳이 서버보다는 브라우저가 되도록 만들기를 원합니다.
